---
title: Seashell Messages
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: michelle.meredyth@gmail.com
description: Science!
baseurl: 
url: https://d1k6a3twock8v1.cloudfront.net
twitter_username: 
github_username: 
theme: minima
plugins:
- jekyll-feed
sass:
  style: compact
